### ISSUE TITLE
Unknown Value in deployment

### ISSUE THREAD

**Issue by goldste** [cloudreach/urly-wurly#12]
Somehow the dev deployment is not working as expected:
![image](https://user-images.githubusercontent.com/58034698/69405687-a48bae00-0d00-11ea-9d55-9e3e9c03e25b.png)

Looking at the stack trace there seems to be something "Unknown" that should be defined... don't know what it could be at the moment.

> I1122 07:56:39.236406   20171 provider_plugin.go:593] Provider[gcp, 0xc0005acea0].Create(urn:pulumi:dev::urly-wurly::gcp:storage/bucket:Bucket::urly-wurly-dev) executing (#props=5)
I1122 07:56:39.236448   20171 rpc.go:70] Marshaling property for RPC[Provider[gcp, 0xc0005acea0].Create(urn:pulumi:dev::urly-wurly::gcp:storage/bucket:Bucket::urly-wurly-dev).inputs]: __defaults={[{forceDestroy} {name} {storageClass}]}
I1122 07:56:39.236493   20171 rpc.go:70] Marshaling property for RPC[Provider[gcp, 0xc0005acea0].Create(urn:pulumi:dev::urly-wurly::gcp:storage/bucket:Bucket::urly-wurly-dev).inputs]: forceDestroy={false}
I1122 07:56:39.236531   20171 rpc.go:70] Marshaling property for RPC[Provider[gcp, 0xc0005acea0].Create(urn:pulumi:dev::urly-wurly::gcp:storage/bucket:Bucket::urly-wurly-dev).inputs]: location={europe}
I1122 07:56:39.236568   20171 rpc.go:70] Marshaling property for RPC[Provider[gcp, 0xc0005acea0].Create(urn:pulumi:dev::urly-wurly::gcp:storage/bucket:Bucket::urly-wurly-dev).inputs]: name={urly-wurly-dev-86fb009}
I1122 07:56:39.236605   20171 rpc.go:70] Marshaling property for RPC[Provider[gcp, 0xc0005acea0].Create(urn:pulumi:dev::urly-wurly::gcp:storage/bucket:Bucket::urly-wurly-dev).inputs]: storageClass={STANDARD}
I1122 07:56:39.239235   20171 eventsink.go:60] Waiting for state to become: [success]
I1122 07:56:39.239312   20171 eventsink.go:63] eventSink::Debug(<{%reset%}>Waiting for state to become: [success]<{%reset%}>)
I1122 07:56:39.561502   20171 provider_plugin.go:1123] provider received rpc error `Unknown`: `googleapi: Error 400: Invalid Value, invalid`
I1122 07:56:39.561576   20171 provider_plugin.go:1126] rpc error kind `Unknown` may not be recoverable
I1122 07:56:39.561610   20171 provider_plugin.go:623] Provider[gcp, 0xc0005acea0].Create(urn:pulumi:dev::urly-wurly::gcp:storage/bucket:Bucket::urly-wurly-dev) failed: googleapi: Error 400: Invalid Value, invalid
I1122 07:56:39.561651   20171 eventsink.go:87] eventSink::Error(<{%reset%}>googleapi: Error 400: Invalid Value, invalid<{%reset%}>)

Anonymized config:
config:
  gcp:project: my-google-project
  gcp:region: europe-west6
  gcp:zone: europe-west6
  urly-wurly:branch: develop
  urly-wurly:domain: ""
  urly-wurly:location: europe-west6
  urly-wurly:owner: me
  urly-wurly:project_name: my-google-project
  urly-wurly:project_number: my-google-project-number
  urly-wurly:repository: my-fork

**Comment by helloworlddan** [comment]
Hi @goldste 

Cloud Run isn't available in europe-west6/Zürich. Check this table for reference: https://cloud.google.com/about/locations/?tab=europe

**Comment by goldste** [comment]
yeah... still doesn't work with europe-west1 because europe is not a recognized location....
there is a bug in index.ts changing:
`// Create GCS bucket to store links
const bucket = new gcp.storage.Bucket(appName, {
  location: locationName.split('-')[0],
});`
to 
`// Create GCS bucket to store links
const bucket = new gcp.storage.Bucket(appName, {
  location: locationName,
});`
And the bucket stuff works well. (Note: this changes the setting also from Multi-Regional to Regional)
