### ISSUE TITLE
Trigger is not executed and variable not used

### ISSUE THREAD

**Issue by goldste** [cloudreach/urly-wurly#13]
Everythins is working as expected. Except the build trigger is not executed.
![image](https://user-images.githubusercontent.com/58034698/69415973-df4c1100-0d15-11ea-91e6-7ea86d95e65a.png)

In addition it seems cloudbuild.yaml doesn't use the variables defined in the Pulumi yaml. If one is using a different region he needs to adjust both files.
https://github.com/cloudreach/urly-wurly/blob/master/ci/cloudbuild.yaml

**Comment by helloworlddan** [comment]
Hi @goldste 

Yes, the build trigger is only executed upon git pushes; it will not execute upon deploying its definitions in Pulumi.

I understand that you'd like to specify a region in the Pulumi config and have that region being fed into cloud build's substitution map. Care to provide a PR?

**Comment by helloworlddan** [comment]
Fixed in https://github.com/cloudreach/urly-wurly/pull/20
