### ISSUE TITLE
Credentials and ClientID adjustments

### ISSUE THREAD

**Issue by goldste** [cloudreach/urly-wurly#15]
Documentation is missing about the configuration for the credentials.
One has to configure the OAuth consent screen and create an OAuth 2.0 client and whitelisting the APP. 
In addition the html in  container/public/index.html needs to be adjusted
`<meta name="google-signin-client_id" content="   <meta name="google-signin-client_id" content="??????.apps.googleusercontent.com">`

**Comment by helloworlddan** [comment]
Hi @goldste !

Documentation on this has been added in #16
