### ISSUE TITLE
URL Encoding

### ISSUE THREAD

**Issue by nsalvo** [cloudreach/urly-wurly#18]
I think I found a bug in urly wurly

this URL: https://azure.microsoft.com/mediahandler/files/resourcefiles/phippy-goes-to-the-zoo/Phippy%20Goes%20To%20The%20Zoo_MSFTonline.pdf
translates to this: https://cldr.ch/3Tfv8u
which gives: https://azure.microsoft.com/mediahandler/files/resourcefiles/phippy-goes-to-the-zoo/Phippy%!G(MISSING)oes%!T(MISSING)o%!T(MISSING)he%!Z(MISSING)oo_MSFTonline.pdf

Is this because is an Azure link? :D

**Comment by helloworlddan** [comment]
Hi @nsalvo !

Thanks for reporting this. I quickly verified this and it seems that there is a URL unescape missing in the shortening endpoint.
